### ISSUE TITLE
BTR incorrectly filtering out CSS

### ISSUE THREAD

**Issue by agubler** [dojo/webpack-contrib#124]
**Bug**

BTR is incorrectly filtering out CSS with nested selectors.

```css
.my-class > a {
    background: red;
}
```

Should consider stripping anything after the `>` character when matching against the class list for filtering.
